{{- range $key, $value := .Values.component }}
{{- if and $value.enabled $value.backendConfigMap.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opik.name" $ }}-{{ $key | lower }}
  labels:
    {{- include "opik.labels" $ | nindent 4 }}
data:
  {{- if eq $key "backend" }}
  {{- if $.Values.minio.enabled }}
  AWS_ACCESS_KEY_ID: {{ $.Values.minio.auth.rootUser | quote }}
  AWS_SECRET_ACCESS_KEY: {{ $.Values.minio.auth.rootPassword | quote }}
  S3_URL: "http://opik-minio:9000"
  {{- else }}
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  IS_MINIO: "false"
  {{- end }}
  PYTHON_EVALUATOR_URL: "http://opik-python-backend:{{ index $.Values.component "python-backend" "env" "PYTHON_BACKEND_PORT" | default "8000" }}"
  {{- end }}
  
  {{- range $envkey, $envvalue := $value.env }}
  {{- if not (and (eq $key "backend") (eq $envkey "PYTHON_EVALUATOR_URL")) }}
  {{ $envkey }}: {{ $envvalue | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}