{{- range $key, $value := .Values.component }}
{{- if and $value.enabled $value.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  {{ include "opik.name" $ }}-{{ $key | lower }}
  namespace: {{ $.Release.Namespace }}
  labels:
    release: {{ $.Release.Name }}
  annotations:
  {{- with $value.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $value.ingress.certificate_arn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ $value.ingress.certificate_arn }}
  {{- end }}
  {{- if $value.ingress.ssl_policy }}
    alb.ingress.kubernetes.io/ssl-policy: {{ $value.ingress.ssl_policy }}
  {{- end }}
spec:
  ingressClassName: {{ default "alb" $value.ingress.ingressClassName }}  
  {{- if and $value.ingress.tls $value.ingress.tls.enabled }}
  tls:
    - hosts:
      {{- if $value.ingress.tls.hosts }}
      {{- range $value.ingress.tls.hosts }}
      - {{ . | quote }}
      {{- end }}
      {{- else }}
      {{- range $value.ingress.hosts }}
      {{- if .host }}
      - {{ .host | quote }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if $value.ingress.tls.secretName }}
      secretName: {{ $value.ingress.tls.secretName }}
      {{- end }}
  {{- end }}
  rules:
  {{- range $value.ingress.hosts }}
  {{- if .host }}
  - host: {{ .host | quote }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          {{- if .action }}
          service:
            name: {{ .action }}
            port:
              name: use-annotation
          {{- else }}
          service:
            name: {{ include "opik.name" $ }}-{{ $key | lower }}
            port:
              number: {{ .port }}
          {{- end }}
      {{- end }}
  {{- end }}
  
{{- end }}
{{- end }}
