repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        files: ^sdks/opik_optimizer
      - id: end-of-file-fixer
        files: ^sdks/opik_optimizer

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
        files: ^sdks/opik_optimizer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      - id: ruff
        args: [ --fix, --show-fixes]
        files: ^sdks/opik_optimizer
      - id: ruff-format
        files: ^sdks/opik_optimizer

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        files: ^sdks/opik_optimizer
        exclude: '(sdks/opik_optimizer/scripts/)'
        args: [--config-file, sdks/opik_optimizer/pyproject.toml, --install-types, --non-interactive]
        additional_dependencies: [types-requests, pytest, pyrate_limiter, modal]
