repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        files: ^apps/opik-guardrails-backend
      - id: end-of-file-fixer
        files: ^apps/opik-guardrails-backend

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff
        args: [ --fix, --show-fixes]
        files: ^apps/opik-guardrails-backend
      - id: ruff-format
        files: ^apps/opik-guardrails-backend

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        files: ^apps/opik-guardrails-backend
        # `exclude` option will work only from here.
        # The rest of mypy configuration can be moved to pyproject.toml
        exclude: '(^apps/opik-guardrails-backend/tests/)|(^apps/opik-guardrails-backend/scripts/)'
        args: [--config-file, apps/opik-guardrails-backend/pyproject.toml]
