repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        args:
          - --print-width=120
        files: ^apps/opik-documentation
        exclude: "^(apps/opik-documentation/documentation/docs/reference)|(apps/opik-documentation/documentation/docs/cookbook/)"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        files: ^apps/opik-documentation
      - id: ruff-format
        files: ^apps/opik-documentation

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        files: ^apps/opik-documentation/.*\.ipynb

  - repo: https://github.com/mwouts/jupytext
    rev: v1.16.1
    hooks:
      - id: jupytext
        args: [--to, markdown]
        files: ^apps/opik-documentation/.*\.ipynb
