name: üóÇÔ∏è Auto Label PR

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  labeler:
    name: PR Labeler - Apply and Sync Labels
    runs-on: ubuntu-latest
    timeout-minutes: 1

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Apply and Sync Labels
        uses: actions/labeler@v5
        with:
          sync-labels: true # Remove labels if the file paths no longer match
          configuration-path: .github/labeler.yml
