# Workflow to run Guar tests
#
# Please read inputs to provide correct values.
#
name: SDK Lib Guardrails Tests
run-name: "SDK Lib Guardrails Tests ${{ github.ref_name }} by @${{ github.actor }}"
permissions:
  contents: read
env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  OPENAI_ORG_ID:  ${{ secrets.OPENAI_ORG_ID }}
  GUARDRAILS_API_KEY: ${{ secrets.GUARDRAILS_API_KEY }}
  OPIK_ENABLE_LITELLM_MODELS_MONITORING: False
  OPIK_SENTRY_ENABLE: False
on:
  workflow_call:

jobs:
  tests:
    name: Guardrails Python ${{matrix.python_version}}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: sdks/python

    strategy:
      fail-fast: true
      matrix:
        python_version: [
          "3.10",
          "3.11",
          "3.12",
          "3.13",
          "3.14"
        ]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python ${{matrix.python_version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python_version}}

      - name: Install opik
        run: pip install .

      - name: Install test tools
        run: |
          cd ./tests
          pip install --no-cache-dir --disable-pip-version-check -r test_requirements.txt

      - name: Install lib 
        run: |
          cd ./tests
          pip install --no-cache-dir --disable-pip-version-check -r library_integration/guardrails/requirements.txt

      - name: Install checks from guardrails hub
        run: |
          guardrails configure --token $GUARDRAILS_API_KEY --disable-metrics --enable-remote-inferencing;
          guardrails hub install hub://guardrails/politeness_check

      - name: Run tests
        run: |
          cd ./tests/library_integration/guardrails/
          python -m pytest  -vv .