name: SDKs Generate OpenAPI spec and Fern code

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update-open-api-spec-and-fern-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Install Fern
        run: npm install -g fern-api

      - name: Set branch name
        run: |
          echo "BRANCH_NAME=update-openapi-spec-and-fern-code-$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Create branch
        uses: JosiahSiegel/remote-branch-action@v1.2.0
        with:
          branch: ${{ env.BRANCH_NAME }}

      - name: Run Generate OpenAPI spec and Fern code
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          set -e
          ./scripts/generate_openapi.sh

      - name: Push files
        uses: comet-ml/push-files@main
        with:
          branch: ${{ env.BRANCH_NAME }}
          files: |
            sdks/python/src/opik/rest_api:sdks/python/src/opik/rest_api
            sdks/typescript/src/opik/rest_api:sdks/typescript/src/opik/rest_api
            sdks/code_generation/fern/openapi/openapi.yaml:sdks/code_generation/fern/openapi/openapi.yaml
            apps/opik-documentation/documentation/fern/openapi/opik.yaml:apps/opik-documentation/documentation/fern/openapi/opik.yaml
          github_token: ${{ secrets.GH_PAT_TO_ACCESS_GITHUB_API }}
          repository: 'comet-ml/opik'
          commit_user_email: github-actions@comet.com
          commit_user_name: 'Github Actions (${{ github.actor }})'
          commit_message: "Update OpenAPI spec and Fern code"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          title: "Update OpenAPI spec and Fern code"
          body: "Automated update of Open API spec and Fern Code after running `./scripts/generate_openapi.sh`"
          base: main
